### ISSUE TITLE
Debug Failing

### ISSUE THREAD

**Issue by mohittyagi11** [gast04/JDB-plus-plus#1]
load debug files
Setup emulator
connect to app
[+] Starting local process '/usr/bin/jdb': pid 50357
waiting
Traceback (most recent call last):
  File "jdb++.py", line 31, in <module>
    header = p.readuntil("Breakpoint hit:", drop=True)
  File "/usr/local/lib/python3.7/site-packages/pwnlib/tubes/tube.py", line 1402, in wrapper
    return func(self, *a, **kw)
  File "/usr/local/lib/python3.7/site-packages/pwnlib/tubes/tube.py", line 310, in recvuntil
    res = self.recv(timeout=self.timeout)
  File "/usr/local/lib/python3.7/site-packages/pwnlib/tubes/tube.py", line 82, in recv
    return self._recv(numb, timeout) or b''
  File "/usr/local/lib/python3.7/site-packages/pwnlib/tubes/tube.py", line 160, in _recv
    if not self.buffer and not self._fillbuffer(timeout):
  File "/usr/local/lib/python3.7/site-packages/pwnlib/tubes/tube.py", line 131, in _fillbuffer
    data = self.recv_raw(self.buffer.get_fill_size())
  File "/usr/local/lib/python3.7/site-packages/pwnlib/tubes/process.py", line 707, in recv_raw
    raise EOFError

**Comment by gast04** [comment]
looks like you didn't set an initial breakpoint in .jdbrc file. 
what have been your steps?

It doesnt automatically set a breakpoint in the first onCreate for the moment, this
is a future todo

**Comment by mohittyagi11** [comment]
I didnt find .jdbrc file so I created one in the home directiory. Still the same issue

**Comment by gast04** [comment]
its not there by default, you also added a line like:
stop in com.testapp.MainActivity.onCreate(android.os.Bundle) 

can you forward the apk? like that I can reproduce it

**Comment by mohittyagi11** [comment]
Yeah I did that.

You can download from play store.

Aarogya setu app

**Comment by gast04** [comment]
ok I gonna test that, 
thanks for the input

**Comment by gast04** [comment]
I made some minor fixes, 
starting the application with "python jdb++.py -n nic.goi.aarogyasetu -a .views.SplashActivity"
works fine for me

Edit:
including the breakpoint
"stop in nic.goi.aarogyasetu.views.SplashActivity.onCreate(android.os.Bundle)"
